### PR TITLE
Made the arrow point from mope.io to deeeep.io

### PR DESCRIPTION
**Pull request by SirReadsALot**
Deeeep.io was inspired by mope.io, so yeah I tried to make an arrow in SVG pointing it that way

### CODE REVIEW

**Comment by getkey** [comment]
Thanks for your contribution! Indeed, looking at the changelogs, mope.io seems to have been released earlier than deeeep.io: https://deeeepio.fandom.com/wiki/Changelogs#Pre-November_4th.2C_2016_.28Release.29 vs https://mope.io/updates.txt

The wayback machine also backs this up https://web.archive.org/web/20160501000000*/mope.io vs https://web.archive.org/web/20160801000000*/deeeep.io

If you have an additional source, such as a statement from the developer, please tell me so we can document it. 🙂 

Could you edit the .gv file rather than the .svg though? I cannot accept changes to the SVG because they will get overwritten. 

Should be easy to do, you just have to modify this

https://github.com/getkey/io-game-history/blob/d49d589a013ce969a8778c681d68c95656402530/io-game-history.gv#L160

Then you can just regenerate the SVG https://github.com/getkey/io-game-history#how-to-generate-this-graph

**Comment by SirReadsALot** [comment]
> Thanks for your contribution! Indeed, looking at the changelogs, mope.io seems to have been released earlier than deeeep.io: https://deeeepio.fandom.com/wiki/Changelogs#Pre-November_4th.2C_2016_.28Release.29 vs https://mope.io/updates.txt
> 
> The wayback machine also backs this up https://web.archive.org/web/20160501000000*/mope.io vs https://web.archive.org/web/20160801000000*/deeeep.io
> 
> If you have an additional source, such as a statement from the developer, please tell me so we can document it. 🙂
> 
> Could you edit the .gv file rather than the .svg though? I cannot accept changes to the SVG because they will get overwritten.
> 
> Should be easy to do, you just have to modify this
> 
> https://github.com/getkey/io-game-history/blob/d49d589a013ce969a8778c681d68c95656402530/io-game-history.gv#L160
> 
> Then you can just regenerate the SVG https://github.com/getkey/io-game-history#how-to-generate-this-graph

Sure here is further proof from the developer himself (all of these were sent in the official discord server)
Capture2
Capture

also I edited the arrow in the .gv file to point towards deeeep.io and I added his name under the game in the svg file :]

**Comment by getkey** [comment]
Thanks, great to have it straight from the dev's mouth!

> I edited the arrow in the .gv file to point towards deeeep.io

Did you push your changes? I don't see the modification to the .gv in your branch

>  I added his name under the game in the svg file :]

You should do that in the .gv too, you just have to add the name as a label like this https://github.com/getkey/io-game-history/blob/d49d589a013ce969a8778c681d68c95656402530/io-game-history.gv#L63

**Comment by getkey** [comment]
Hey @SirReadsALot! :slightly_smiling_face: Are you still interested in submitting your changes to this PR?

**Comment by getkey** [comment]
Just made the change, so closing. Thanks for opening this PR :slightly_smiling_face:

**Pull request closed without merging**
